### ISSUE TITLE
Caused by: jakarta.jms.JMSException: java.lang.LinkageError: ClassCastException: attempting to castjar:file:/<repo-path>/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-

### ISSUE THREAD

**Issue by fanimali** [datastax/pulsar-jms#162]
Hi, user is getting this error when building version pulsar-jms 7.0.1:

`Caused by: jakarta.jms.JMSException: java.lang.LinkageError: ClassCastException: attempting to castjar:file:/<repo-path>/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/<repo-path>/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class
at com.datastax.oss.pulsar.jms.Utils.handleException(Utils.java:74) ~[pulsar-jms-7.0.1.jar:na]
at com.datastax.oss.pulsar.jms.PulsarConnectionFactory.ensureInitialized(PulsarConnectionFactory.java:580) ~[pulsar-jms-7.0.1.jar:na]
at com.datastax.oss.pulsar.jms.PulsarConnectionFactory.createConnection(PulsarConnectionFactory.java:670) ~[pulsar-jms-7.0.1.jar:na]
at com.datastax.oss.pulsar.jms.PulsarConnectionFactory.createConnection(PulsarConnectionFactory.java:101) ~[pulsar-jms-7.0.1.jar:na]
at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:211) ~[spring-jms-6.1.10.jar:6.1.10]
at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:517) ~[spring-jms-6.1.10.jar:6.1.10]
... 23 common frames omitted
Caused by: java.lang.LinkageError: ClassCastException: attempting to castjar:file:/<repo-path>/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/<repo-path>/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class
at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:105) ~[javax.ws.rs-api-2.1.jar:2.1]
at org.apache.pulsar.client.admin.internal.PulsarAdminImpl.<init>(PulsarAdminImpl.java:136) ~[pulsar-client-admin-original-3.2.3.jar:3.2.3]
at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:44) ~[pulsar-client-admin-original-3.2.3.jar:3.2.3]
at com.datastax.oss.pulsar.jms.PulsarConnectionFactory.ensureInitialized(PulsarConnectionFactory.java:528) ~[pulsar-jms-7.0.1.jar:na]
... 27 common frames omitted
Collapse`

customer is building with the **pulsar-jms** thin jar, but when they build with the **pulsar-jms-all** jar they don't see any problem.

**Comment by fanimali** [comment]
hi @eolivelli is there a new release that I can send to customer to test?

**Comment by fanimali** [comment]
@mukesh-ctds can yuo help here? customer has escalated this
