### ISSUE TITLE
org.conscrypt.Conscrypt error at jboss startup

### ISSUE THREAD

**Issue by akhil1000** [datastax/pulsar-jms#43]
I've been getting this error at startup. This error has no impact as everything is working but shows up in the log at startup. Not sure if we should add a dependency for this 

2022-06-08 08:40:28,813 WARN [org.apache.pulsar.common.util.SecurityUtility] Conscrypt isn't available. Using JDK default security provider.
java.lang.ClassNotFoundException: org.conscrypt.Conscrypt from BaseClassLoader@e49b3c{vfszip:/usr/jboss/server/sync/deploy/mdm/jms/pulsarra-rar.rar/}
at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:477)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at org.apache.pulsar.common.util.SecurityUtility.loadConscryptProvider(SecurityUtility.java:122)
at org.apache.pulsar.common.util.SecurityUtility.<clinit>(SecurityUtility.java:79)
at org.apache.pulsar.client.impl.PulsarChannelInitializer.lambda$new$0(PulsarChannelInitializer.java:120)
at org.apache.pulsar.client.util.ObjectCache.get(ObjectCache.java:48)
at org.apache.pulsar.client.impl.PulsarChannelInitializer.lambda$initTls$1(PulsarChannelInitializer.java:169)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Unknown Source)
20

**Comment by eolivelli** [comment]
I cannot reproduce this error.
in this integration test we deploy the .rar file in Apache TomEE with docker
https://github.com/datastax/pulsar-jms/blob/a53f665380480f9c2fb5da5b5cef1e1949519a43/resource-adapter-tests/src/test/java/com/datastax/oss/pulsar/jms/tests/DockerTest.java#L35
the logs are clean.

Are you running jBoss in some container ?
which OS ?
which JDK ?
