### ISSUE TITLE
Closing QueueRequestor triggers "org.apache.pulsar.client.admin.PulsarAdminException$PreconditionFailedException: Topic has active producers/subscriptions"

### ISSUE THREAD

**Issue by yabinmeng** [datastax/pulsar-jms#9]
I'm simulating a JMS QueueRequestor behavior against Pulsar server. The code is below. Basically I'm using the QueueRequestor to send 5 messages with payload of an integer for each message. The receiver side times the integer value by 100 and  sends it back. 

```
    void demo() throws JMSException {
        if (queueSession != null) {
            queueConnection.start();
            QueueRequestor queueRequestor = new QueueRequestor(queueSession, queue);

            for (int i = 0; i < 5; i++) {
                Message message = queueSession.createTextMessage(String.valueOf(RandomUtils.nextInt(0, 10)));
                message.setJMSReplyTo(replyQueue);

                Message response = queueRequestor.request(message);
                System.out.println("QueueRequestorClient:: sent message " + (String)message.getBody(String.class));
                System.out.println("QueueRequestorClient:: received response message " + (String)response.getBody(String.class));
            }

            queueRequestor.close();
            queueConnection.stop();
        }
    }
```

The code mostly works fine except that when I try to close the QueueRequestor. The command line output is as below:
```
QueueRequestorClient:: sent message 8
QueueRequestorClient:: received response message 800
QueueRequestorClient:: sent message 2
QueueRequestorClient:: received response message 200
QueueRequestorClient:: sent message 1
QueueRequestorClient:: received response message 100
QueueRequestorClient:: sent message 8
QueueRequestorClient:: received response message 800
QueueRequestorClient:: sent message 1
QueueRequestorClient:: received response message 100
[pulsar-client-io-5-1] INFO org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/jms-temp-queue-cff31689-cec1-430b-a416-fcdacdd57ab5] [jms-queue] Closed consumer
[main] INFO com.datastax.oss.pulsar.jms.PulsarTemporaryDestination - Deleting TemporaryQueue{persistent://public/default/jms-temp-queue-cff31689-cec1-430b-a416-fcdacdd57ab5}
[main] INFO com.datastax.oss.pulsar.jms.PulsarTemporaryDestination - Stats TopicStatsImpl(count=0, msgRateIn=0.0, msgThroughputIn=0.0, msgRateOut=0.0, msgThroughputOut=0.0, bytesInCounter=905, msgInCounter=5, bytesOutCounter=905, msgOutCounter=5, averageMsgSize=0.0, msgChunkPublished=false, storageSize=905, backlogSize=905, offloadedStorageSize=0, publishers=[PublisherStatsImpl(count=0, accessMode=Shared, msgRateIn=0.0, msgThroughputIn=0.0, averageMsgSize=0.0, chunkedMessageRate=0.0, producerId=2, producerNameOffset=96, producerNameLength=13, addressOffset=109, addressLength=19, connectedSinceOffset=64, connectedSinceLength=27, clientVersionOffset=91, clientVersionLength=5, stringBuffer=/10.151.6.112:654102021-10-08T22:45:50.494239Z2.8.0clusterA-1-572021-10-08T22:45:50.494239Z2.8.0clusterA-1-57/10.151.6.112:65410, metadata={})], waitingPublishers=0, subscriptions={jms-queue=SubscriptionStatsImpl(msgRateOut=0.0, msgThroughputOut=0.0, bytesOutCounter=905, msgOutCounter=5, msgRateRedeliver=0.0, chunkedMessageRate=0, msgBacklog=0, backlogSize=0, msgBacklogNoDelayed=0, blockedSubscriptionOnUnackedMsgs=false, msgDelayed=0, unackedMessages=0, type=Shared, activeConsumerName=null, msgRateExpired=0.0, totalMsgExpired=0, lastExpireTimestamp=0, lastConsumedFlowTimestamp=1633733150380, lastConsumedTimestamp=0, lastAckedTimestamp=0, lastMarkDeleteAdvancedTimestamp=1633733151059, consumers=[], isDurable=true, isReplicated=false, consumersAfterMarkDeletePosition={}, nonContiguousDeletedMessagesRanges=0, nonContiguousDeletedMessagesRangesSerializedSize=0)}, replication={}, deduplicationStatus=Enabled, topicEpoch=null, nonContiguousDeletedMessagesRanges=0, nonContiguousDeletedMessagesRangesSerializedSize=0)
[AsyncHttpClient-11-1] WARN org.apache.pulsar.client.admin.internal.BaseResource - [http://10.101.32.181:8080/admin/v2/persistent/public/default/jms-temp-queue-cff31689-cec1-430b-a416-fcdacdd57ab5?force=false&deleteSchema=true] Failed to perform http delete request: javax.ws.rs.ClientErrorException: HTTP 412 Precondition Failed
javax.jms.JMSException: org.apache.pulsar.client.admin.PulsarAdminException$PreconditionFailedException: Topic has active producers/subscriptions
	at com.datastax.oss.pulsar.jms.Utils.handleException(Utils.java:63)
	at com.datastax.oss.pulsar.jms.PulsarTemporaryDestination.delete(PulsarTemporaryDestination.java:59)
	at javax.jms.QueueRequestor.close(QueueRequestor.java:101)
	at com.example.jms.queue_pattern.QueueRequestorClient.demo(QueueRequestorClient.java:33)
	at com.example.jms.queue_pattern.QueuePatternDemo.main(QueuePatternDemo.java:162)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException$PreconditionFailedException: Topic has active producers/subscriptions
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:236)
	at org.apache.pulsar.client.admin.internal.BaseResource$3.failed(BaseResource.java:184)
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
```

The other issue that I noticed that for each message I set JMSReplyTo to a named topic (e.g. "persistent://public/default/requestor_temp"). On the receiver side when it gets the reply queue from the message, it returns a temporary queue name (e.g. "persistent://public/default/jms-temp-queue-xxx). This doesn't look right to me.

**Comment by eolivelli** [comment]
For the first problem there is an option to force the deletion of temporary topics
https://github.com/datastax/pulsar-jms/blob/1f7424ce3ed34934e63077a909bdfba77a072ff4/pulsar-jms/src/main/java/com/datastax/oss/pulsar/jms/PulsarConnectionFactory.java#L255
